#!/bin/bash
loop=0
for (( ; ; ))
do
  
  time=$(date +'%s')
  #echo $time
  myArray=("./temp/totalhosts" "./temp/requiredhosts" "./temp/hostnames")
  for str in ${myArray[@]}; do
    if [ -f $str ]; then
	    rm $str
    fi
  done
  echo $(date +"%T") reading no of servers required as per servers.conf file 
  serverscount=`cat server.conf`
	#echo $serverscount 
  . $1
  openstack server list -f value >> ./temp/totalhosts && grep -nr "$2_network" ./temp/totalhosts > ./temp/requiredhosts && awk '{print $2}' ./temp/requiredhosts >> ./temp/hostnames
  noofservers=0
  for i in `cat ./temp/hostnames`
  do
    
    if [ $i != $2_haproxy ] && [ $i != $2_bastion ]
      then
        noofservers=$(( $noofservers + 1 )) 
    fi
  done 
  if [ $serverscount -gt $noofservers ]
  then 
    echo $(date +"%T") we need to deploy $(( $serverscount - $noofservers)) servers
    
    myArray=("./temp/totalhosts" "./temp/requiredhosts" "./temp/hostnames" "./temp/namesofhost")
    for str in ${myArray[@]}; do
      if [ -f $str ]; then
	      rm $str
      fi
    done
    for ((i = 1 ; i <= $serverscount ; i++)); do
      echo "$2_dev$i" >> ./temp/hostnames
    done
    echo $(date +"%T") running the playbook
    ansible-playbook -i hosts deployservers.yaml
    echo $(date +"%T") confirming ping once again 
    ansible-playbook -i hosts ping.yaml
    echo $(date +"%T") installing flask
    ansible-playbook -i hosts flasksnmp.yaml
  elif [ $serverscount -lt $noofservers ]
  then 
    echo $(date +"%T") delete the extra $(( $noofservers - $serverscount )) servers
    myArray=("./temp/totalhosts" "./temp/requiredhosts" "./temp/hostnames" "./temp/namesofhost" )
    for str in ${myArray[@]}; do
      if [ -f $str ]; then
	      rm $str
      fi
    done
    for ((i = $noofservers ; i > $serverscount ; i--)); do
      echo "$2_dev$i" >> ./temp/hostnames
    done
    echo $(date +"%T") running the playbook
    ansible-playbook -i hosts deleteservers.yaml
    if [ $serverscount -gt 0 ];then
      if [ $loop == 0 ];then 
        echo $(date +"%T") for the first time runnning operate it installs flask  
        ansible-playbook -i hosts flasksnmp.yaml 
      else 
        echo $(date +"%T") update the haproxy 
        ansible-playbook -i hosts haproxytest.yaml
      fi
    fi
    time1=$(date +'%s')
    time2=$(( $time1 - $time ))
    if [ $time2 -lt 30 ]
    then
      time2=$(( 30 - $time2 ))
      echo $(date +"%T") we are having zero number of servers ....sleeping for $time2 seconds
      sleep $time2
    fi
  else
    if [ $loop == 0 ];then
      echo $(date +"%T") for the first time runnning operate it installs flask 
      ansible-playbook -i hosts flasksnmp.yaml
    else
      time1=$(date +'%s')
      time2=$(( $time1 - $time ))
      if [ $time2 -lt 30 ]
      then
        time2=$(( 30 - $time2 ))
        echo $(date +"%T") we are having required number of servers ....sleeping for $time2 seconds
        sleep $time2
      fi
    fi
  fi 
  loop=$(( $loop + 1 ))
done

#. $1
#ansible-playbook -i hosts openstack2.yaml
#echo confirming ping once again 
#ansible-playbook -i hosts ping.yaml

#ansible-playbook -i hosts flasksnmp.yaml

